controller_list:
  - name: fake_arm1_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_01_joint_01
      - arm_01_joint_02
      - arm_01_joint_03
      - arm_01_joint_04
      - arm_01_joint_05
      - arm_01_joint_06
  - name: fake_arm2_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_02_joint_01
      - arm_02_joint_02
      - arm_02_joint_03
      - arm_02_joint_04
      - arm_02_joint_05
      - arm_02_joint_06
  - name: fake_arm3_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_03_joint_01
      - arm_03_joint_02
      - arm_03_joint_03
      - arm_03_joint_04
      - arm_03_joint_05
      - arm_03_joint_06
  - name: fake_dock1_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_dock2_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_dock3_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: arm1
    pose: stand
  - group: arm2
    pose: stand
  - group: arm3
    pose: stand