# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.9
default_acceleration_scaling_factor: 0.2

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm_01_joint_01:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  arm_01_joint_02:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  arm_01_joint_03:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  arm_01_joint_04:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  arm_01_joint_05:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  arm_01_joint_06:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  arm_02_joint_01:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  arm_02_joint_02:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  arm_02_joint_03:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  arm_02_joint_04:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  arm_02_joint_05:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  arm_02_joint_06:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  arm_03_joint_01:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  arm_03_joint_02:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  arm_03_joint_03:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  arm_03_joint_04:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  arm_03_joint_05:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  arm_03_joint_06:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5